del FileList.txt
del LGPL.TXT
del License.txt
del PotScreenSaver.scr
del uninstall.exe
del History\Chinese(Simplified).txt
del History\Chinese(Traditional).txt
del History\Hungarian.txt
del History\Japanese.txt
del History\Korean.txt
del History\Polish.txt
del History\Serbian.txt
del History\Ukrainian.txt
del IconPack\OldIconPack.dll
del Language\Armenian.ini
del Language\Azerbaijan.ini
del Language\Bulgarian.ini
del Language\Chinese(Simplified).ini
del Language\Chinese(Traditional).ini
del Language\Czech.ini
del Language\French.ini
del Language\German.ini
del Language\Greek.ini
del Language\Hebrew.ini
del Language\Hongkonglocale.ini
del Language\Hungarian.ini
del Language\Indonesian.ini
del Language\Italian.ini
del Language\Japanese.ini
del Language\Korean.ini
del Language\Persian.ini
del Language\Polish.ini
del Language\Portuguese.ini
del Language\Serbian.ini
del Language\Spanish.ini
del Language\Swedish.ini
del Language\Tajik(Cyrillic).ini
del Language\Thai.ini
del Language\Turkish.ini
del Language\Uzbek(Latin).ini
del Module\FFmpeg\FFmpeg.dll
del /Q Module\OpenCodec
del Module\libmfxsw32.dll
del Skins\WindowFrame.dsf
del DaumCrashHandler64.dll