del {app}\Language\Armenian.ini
del {app}\Language\Azerbaijan.ini
del {app}\Language\Bulgarian.ini
del {app}\Language\Chinese(Simplified).ini
del {app}\Language\Chinese(Traditional).ini
del {app}\Language\Czech.ini
del {app}\Language\French.ini
del {app}\Language\German.ini
del {app}\Language\Greek.ini
del {app}\Language\Hebrew.ini
del {app}\Language\Hongkonglocale.ini
del {app}\Language\Hungarian.ini
del {app}\Language\Indonesian.ini
del {app}\Language\Italian.ini
del {app}\Language\Japanese.ini
del {app}\Language\Korean.ini
del {app}\Language\Persian.ini
del {app}\Language\Polish.ini
del {app}\Language\Portuguese.ini
del {app}\Language\Serbian.ini
del {app}\Language\Spanish.ini
del {app}\Language\Swedish.ini
del {app}\Language\Tajik(Cyrillic).ini
del {app}\Language\Thai.ini
del {app}\Language\Turkish.ini
del {app}\Language\Uzbek(Latin).ini
del {app}\IconPack\OldIconPack.dll
del {app}\History\Chinese(Simplified).txt
del {app}\History\Chinese(Traditional).txt
del {app}\History\Hungarian.txt
del {app}\History\Japanese.txt
del {app}\History\Korean.txt
del {app}\History\Polish.txt
del {app}\History\Serbian.txt
del {app}\Module\OpenCodec